### ISSUE TITLE
Small issue

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_ed_resize#1]
from https://github.com/Alexey-T/CudaText/issues/3160
quote:
@halfbrained Sometimes I face a small problem, e.g.,

- Open 4 groups
- Focus g2 and minimize it (Alt+M)
- Focus go to another tab
- Just minimize it (Alt+M)
- Focus go to another tab
- Now, **JUST SINGLE CLICK** to the other which is not minimized to get focused (single click, not multiple clicks).
- Maximize it (Alt+X)
- It does not get maximized but a minimized tab gets opened.

Does you face the same incident?

**Comment by halfbrained** [comment]
@GHNewbiee New version should fix this

**Comment by Alexey-T** [comment]
@GHNewbiee plugin is updated in Github repo,
https://github.com/halfbrained/cuda_ed_resize
pls do "Install from Github" in AddonManager to test this fix.

**Comment by GHNewbiee** [comment]
@halfbrained & @Alexey-T Thanks both of you!

Unfortunately, I get the following error during installation. Please advise.

![Screenshot from 2021-03-11 17-18-25](https://user-images.githubusercontent.com/26875662/110818885-f5c10780-828d-11eb-9c72-9607f908589b.png)

**Comment by GHNewbiee** [comment]
![Screenshot from 2021-03-11 17-35-42](https://user-images.githubusercontent.com/26875662/110821341-433e7400-8290-11eb-8acf-cdc1bb27659b.png)

After `OK` I get the previous error.

**Comment by Alexey-T** [comment]
It shows that GH site has temporary problems.

**Comment by halfbrained** [comment]
I get the same error if after entering url I choose 'Download as zip' in the next dialog.
But works fine if I choose 'Clone repo' there.

**Comment by halfbrained** [comment]
@Alexey-T Maybe it's because my main branch called 'main' instead of 'master'?
Because I can download this:
https://github.com/halfbrained/cuda_ed_resize/zipball/main
...but if I replace `main` with `master` at the end (url that addon man uses) I get 404

**Comment by Alexey-T** [comment]
yes,you are right: made a fix in Adddon Manager now.

**Comment by GHNewbiee** [comment]
*v.2021.3.11*

It works OK!

**Comment by Alexey-T** [comment]
closing. Pls next issues- new topics.
